using System;
using System.Collections.Generic;

#nullable disable

namespace LCA.Data.Domain
{
    public partial class Epdlayout
    {
        public int Id { get; set; }
        public string EpdlistName { get; set; }
        public string Epdversion { get; set; }
        public string Epdlanguage { get; set; }
        public string EpdsubTxt { get; set; }
        public string Epdheading { get; set; }
        public string EpdheadingSub { get; set; }
        public string Epdowner { get; set; }
        public string EpdownerTxt { get; set; }
        public string Epdoperator { get; set; }
        public string EpdoperatorTxt { get; set; }
        public string Epdpublisher { get; set; }
        public string EpdpublisherTxt { get; set; }
        public string EpddeclarationNo { get; set; }
        public string EpdpublishingNo { get; set; }
        public string Epddecono { get; set; }
        public string Epdapproved { get; set; }
        public string Epdvalid { get; set; }
        public string Epdname { get; set; }
        public string Epdlogo { get; set; }
        public string EpdmainPicture { get; set; }
        public string EpdgeneralHeading { get; set; }
        public string Epdproducer { get; set; }
        public string EpdproductionSite { get; set; }
        public string EpdqualitySystem { get; set; }
        public string Epdpcr { get; set; }
        public string Epdpcrtxt { get; set; }
        public string EpdcompanyNo { get; set; }
        public string Epddeclaration { get; set; }
        public string EpddeclarationTxt { get; set; }
        public string Epdyear { get; set; }
        public string Epdunit { get; set; }
        public string EpdunitOption { get; set; }
        public string EpdunitOptionTxt { get; set; }
        public string Epdcompare { get; set; }
        public string EpdcompareTxt { get; set; }
        public string Epdstudy { get; set; }
        public string Epdverificatior { get; set; }
        public string EpdverificatiorTxt { get; set; }
        public string Epdintern { get; set; }
        public string Epdextern { get; set; }
        public string Epd3party { get; set; }
        public string Epd3partyName { get; set; }
        public string Epd3partySubTxt { get; set; }
        public string EpdapprovedBy { get; set; }
        public string EpdapprovedByTxt { get; set; }
        public string EpdproductHeading { get; set; }
        public string EpdproductDescrition { get; set; }
        public string EpdproductDescritionTxt { get; set; }
        public string EpdproductSpesification { get; set; }
        public string EpdproductSpesificationTxt { get; set; }
        public string EpdproductSpesificationTable { get; set; }
        public string EpdproductTechical { get; set; }
        public string EpdproductTechicalTxt { get; set; }
        public string EpdproductMarket { get; set; }
        public string EpdproductMarketTxt { get; set; }
        public string EpdproductLife { get; set; }
        public string EpdproductLifeTxt { get; set; }
        public string Epdlcaheading { get; set; }
        public string EpddeclarationTxt2 { get; set; }
        public string Epdsystem { get; set; }
        public string EpdsystemTxt { get; set; }
        public string EpdsystemTxt2 { get; set; }
        public string EpddataQuality { get; set; }
        public string EpddataQualityTxt { get; set; }
        public string Epdallocation { get; set; }
        public string EpdallocationTxt { get; set; }
        public string Epdcutoff { get; set; }
        public string EpdcutoffTxt { get; set; }
        public string EpdlcasenariosHeading { get; set; }
        public string EpdlcasenariosHeadingTxt { get; set; }
        public string Epda4heading { get; set; }
        public string Epda5heading { get; set; }
        public string Epdb1heading { get; set; }
        public string Epdb2b3heading { get; set; }
        public string Epdb4b5heading { get; set; }
        public string Epdb6b7heading { get; set; }
        public string Epdc1c3c4heading { get; set; }
        public string Epdc2heading { get; set; }
        public string Epdc2headingTxt { get; set; }
        public string Epdd1heading { get; set; }
        public string EpdlcaresultHeading { get; set; }
        public string EpdlcaresultTxt { get; set; }
        public string EpdsystemHeading { get; set; }
        public string EpdsystemSubTxt { get; set; }
        public string EpdenviromentHeading { get; set; }
        public string EpdenviromentSubTxt { get; set; }
        public string EpdresressourcesHeading { get; set; }
        public string EpdressourcesSubTxt { get; set; }
        public string EpdendOfLifeWasteHeading { get; set; }
        public string EpdendOfLifeWasteSubTxt { get; set; }
        public string EpdendOfLifeFactorHeading { get; set; }
        public string EpdendOfLifeFactorSubTxt { get; set; }
        public string EpdnoaddHeading { get; set; }
        public long? UserId { get; set; }
        public DateTime? Date { get; set; }
        public string Comments { get; set; }
        public string Epddescription { get; set; }
        public string Epdpicture1 { get; set; }
        public string Epdpicture2 { get; set; }
        public string EpdnoaddTxt { get; set; }
        public string EpdapprovedName { get; set; }
        public string EpdnoaddDanger1 { get; set; }
        public string EpdnoaddDanger2 { get; set; }
        public string EpdnoaddDanger3 { get; set; }
        public string EpdnoaddDanger4 { get; set; }
        public string EpdbiblHead { get; set; }
        public string EpdbiblTxt { get; set; }
        public string A1txt { get; set; }
        public string A2txt { get; set; }
        public string A3txt { get; set; }
        public string A4txt { get; set; }
        public string A5txt { get; set; }
        public string B1txt { get; set; }
        public string B2txt { get; set; }
        public string B3txt { get; set; }
        public string B4txt { get; set; }
        public string B5txt { get; set; }
        public string B6txt { get; set; }
        public string B7txt { get; set; }
        public string C1txt { get; set; }
        public string C2txt { get; set; }
        public string C3txt { get; set; }
        public string C4txt { get; set; }
        public string D1txt { get; set; }
        public string Epdnoaddsubhead1 { get; set; }
        public string Epdnoaddsubhead1Txt { get; set; }
        public string Epdnoaddsubhead2 { get; set; }
        public string Epdnoaddsubhead2Txt { get; set; }
        public string Epdnoaddsubhead3 { get; set; }
        public string Epdnoaddsubhead3Txt { get; set; }
        public string Epddoneby { get; set; }
        public string EpddonebyTxt { get; set; }
        public string EpddonebyReg { get; set; }
        public string EpddonebyCon { get; set; }
        public string Epdaddtech { get; set; }
        public string EpdaddtechTxt { get; set; }
        public string Epdbuildinglife { get; set; }
        public long? ComId { get; set; }
        public string Epdsign { get; set; }
        public string Epdlogo2 { get; set; }
        public int? ClientGroupsId { get; set; }
        public int? Epdauthor { get; set; }
        public string Epdnoaddsubhead4 { get; set; }
        public string Epdnoaddsubhead4Txt { get; set; }
        public long? Epd3partyNameId { get; set; }
        public int? Suma1a3 { get; set; }
        public string EpdtoolInfo { get; set; }
        public string EpdtoolInfoTxt { get; set; }
        public string EpdnoaddDanger5 { get; set; }
        public string EpdmainContact { get; set; }
        public string Epdphone { get; set; }
        public string Epdemail { get; set; }
        public string Epdweb { get; set; }
        public string EpdfuncUnit { get; set; }
        public string EpdlcaresultSubTxt { get; set; }
        public string EpdoperatorPublisher { get; set; }
        public string EpdauthorHeading { get; set; }
        public string EpdtoolDeveloperHeading { get; set; }
        public string EpdlcaresultSubTxt2 { get; set; }
    }
}
